Repository neptune588/Picket-FE, pull requests merged in 2023-12, with the labels that each got.

#2 Feat/#1 develop environment settings
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.jsx
  src/assets/react.svg
  src/main.jsx
  vite.config.js
Labels: feat, fix

#7 Feat/#5 thumnail card and common components mock up
  .eslintrc.cjs
  package-lock.json
  package.json
  public/images/test_avatar.jpg
  public/images/test_thumnail.jpg
  src/assets/fonts/font.css
  src/assets/icons/heart.svg
  src/assets/icons/scrap.svg
  src/components/CardBirthView/CardBirthView.jsx
  src/components/CardContent/CardContent.jsx
  src/components/CardTitle/CardTitle.jsx
  src/components/HomeThumnailCard/index.jsx
  src/components/HomeThumnailCard/style.js
  src/components/LikeButton/LikeButton.jsx
  src/components/ProfileAvatar/ProfileAvatar.jsx
  src/components/ScrapButton/ScrapButton.jsx
  src/components/ThumnailCard/index.jsx
  src/components/ThumnailCard/style.js
  src/components/ThumnailImg/ThumnailImg.jsx
  src/pages/Layout.jsx
  src/pages/OnlyTest/OnlyTest.jsx
  src/pages/RouterTest.jsx
  src/routes/router.jsx
  src/styles/GlobalStyle.jsx
  src/styles/theme.js
  vite.config.js
Labels: feat, fix

#9 Feat/#6 navbar categories bucket
  public/images/magnifyingGlass.png
  public/images/test_photo.jpg
  public/images/test_replier.jpg
  public/images/test_writer.jpg
  src/assets/icons/alarm.svg
  src/assets/icons/ellipse.svg
  src/assets/icons/reply.svg
  src/assets/icons/symbol.svg
  src/assets/icons/threedot.svg
  src/components/Bucket/Bucket.jsx
  src/components/Bucket/style.js
  src/components/Categories/Categories.jsx
  src/components/NavBar/Navbar.jsx
  src/pages/TestAlarm/TestAlarm.jsx
  src/pages/TestMain/TestMain.jsx
  src/pages/TestMypage/TestMypage.jsx
  src/pages/TestSearch/TestSearch.jsx
  src/routes/router.jsx
Labels: feat

#11 navBar 마진 수정 및 버킷 댓글위치 조정
  src/components/Bucket/Bucket.jsx
  src/components/Bucket/style.js
  src/components/Categories/Categories.jsx
  src/components/NavBar/Navbar.jsx
  src/pages/Layout.jsx
  src/pages/TestMain/TestMain.jsx
  src/pages/TestSearch/TestSearch.jsx
Labels: fix

#13 Feat/#8 sign in and sign up page
  src/App.jsx
  src/assets/icons/check.svg
  src/assets/spinner.gif
  src/components/CheckBox/index.jsx
  src/components/CheckBox/style.js
  src/components/Input/Input.jsx
  src/components/SiteLoading/SiteLoading.jsx
  src/components/SubmitButton/SubmitButton.jsx
  src/hooks/useSignIn.js
  src/hooks/useSignUp.js
  src/pages/AuthPageLayOut.jsx
  src/pages/Layout.jsx
  src/pages/RegisterSuccess/RegisterSuccess.jsx
  src/pages/SignIn/index.jsx
  src/pages/SignIn/inputData.js
  src/pages/SignIn/style.js
  src/pages/SignUp/dataRefine.js
  src/pages/SignUp/index.jsx
  src/pages/SignUp/inputData.js
  src/pages/SignUp/style.js
  src/pages/SignUp/vaildCheck.js
  src/routes/router.jsx
  src/services/api/index.js
  src/styles/theme.js
  src/utils/userAuthRegex.js
  vite.config.js
  vite.config.js.timestamp-1703173910047-c662bae9f291e.mjs
Labels: feat

#12 Feat/#10 mainpage
  package-lock.json
  package.json
  public/images/ellipse.png
  public/images/main_bucket.png
  src/assets/icons/addbutton.svg
  src/assets/icons/coloredbell.svg
  src/assets/icons/uploadbox.svg
  src/components/AddBucket/AddBucketIcon.jsx
  src/components/AddBucket/AddBucketTitle.jsx
  src/components/AddBucketAlarm/AddBucketAlarm.jsx
  src/components/AddBucketAlarm/AlarmBox.jsx
  src/components/AddBucketAlarm/Calendar.jsx
  src/components/AddBucketAlarm/MovementBtn.jsx
  src/components/AddBucketAlarm/SetAlarm.jsx
  src/components/AddBucketAlarm/SetPublic.jsx
  src/components/AddBucketAlarm/calender_style.js
  src/components/AddBucketImage/AddImg.jsx
  src/components/AddBucketImage/Content.jsx
  src/components/AddBucketImage/DetailBox.jsx
  src/components/AddBucketImage/NextBtn.jsx
  src/components/AddBucketImage/Tags.jsx
  src/components/AddBucketImage/Title.jsx
  src/components/Alarm/AlarmTitle.jsx
  src/components/Bucket/Bucket.jsx
  src/components/Bucket/style.js
  src/components/Categories/Categories.jsx
  src/components/NavBar/Navbar.jsx
  src/components/ProfileEditModal/ProfileEditModal.jsx
  src/components/ProfileEditModal/ProfileImg.jsx
  src/components/ToggleBtn/ToggleBtn.jsx
  src/components/UploadBox/UploadBox.jsx
  src/pages/Layout.jsx
  src/pages/TestAddBucket/TestAddBucket.jsx
  src/pages/TestAlarm/TestAlarm.jsx
  src/pages/TestMain/TestMain.jsx
  src/pages/TestMypage/TestMypage.jsx
  src/pages/TestProfile/TestProfile.jsx
  src/routes/router.jsx
Labels: feat

#15 feat:#14 로그인/로그아웃 기능 구현 완료 + proxy server설정 제거
  src/components/NavBar/Navbar.jsx
  src/hooks/useSignIn.js
  src/services/api/index.js
  vite.config.js
Labels: feat

#19 Feat/#16 mainpage func
  src/components/AddBucketAlarm/AlarmBox.jsx
  src/components/AddBucketAlarm/MovementBtn.jsx
  src/components/AddBucketAlarm/SetAlarm.jsx
  src/components/AddBucketAlarm/calender_style.js
  src/components/AddBucketImage/AddImg.jsx
  src/components/AddBucketImage/Content.jsx
  src/components/AddBucketImage/DetailBox.jsx
  src/components/AddBucketImage/Tags.jsx
  src/components/AddBucketImage/Title.jsx
  src/components/AddBucketImage/styles.js
  src/components/Bucket/Bucket.jsx
  src/components/Bucket/BucketHandleModal.jsx
  src/components/Categories/Categories.jsx
  src/components/HomeThumnailCard/index.jsx
  src/components/HomeThumnailCard/style.js
  src/components/NavBar/index.jsx
  src/components/NavBar/style.js
  src/components/ProfileEditModal/ProfileEditModal.jsx
  src/components/UploadBox/UploadBox.jsx
  src/pages/OnlyTest/OnlyTest.jsx
  src/pages/TestAddBucket/dataRefine.js
  src/pages/TestAddBucket/inputData.js
  src/pages/TestMain/TestMain.jsx
  src/pages/TestProfile/TestProfile.jsx
Labels: bug, feat

#22 Feat/#16 mainpage func
  package-lock.json
  package.json
  public/images/no-image.png
  src/components/Bucket/Bucket.jsx
  src/components/Bucket/style.js
  src/components/HomeThumnailCard/index.jsx
  src/components/NavBar/style.js
  src/components/ProfileEditModal/ProfileEditModal.jsx
  src/pages/OnlyTest/OnlyTest.jsx
  src/pages/TestMain/TestMain.jsx
  src/pages/TestProfile/TestProfile.jsx
  vite.config.js
Labels: feat
